export const events = [
    { id: 11, content: 'Gli esseri umani si nutrono ancora principalmente di raccolta', start: "-030000-01-01", categories: ['Preistoria', 'Società'], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi." },
    { id: 12, content: 'Migrazione umana in America via le coste', start: "-016000-01-01", categories: ['Preistoria', 'Migrazioni'], description: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",  path: [
        [41.3874, 2.1686],  // Barcellona, Spagna
        [43.2965, 5.3698],  // Marsiglia, Francia
        [45.9237, 6.8694],  // Passo del Monginevro (Alpi)
        [44.4949, 11.3426]  // Bologna, Italia
      ] }, // Mock, posizione generica in Brasile
    { id: 13, content: 'Inizio del rapporto tra uomo e cane, domesticazione del lupo', start: "-015000-01-01", categories: ['Preistoria', 'Tecnologia', 'Società'], description: "Quisque sit amet est et sapien ullamcorper pharetra.", position: [40.7128, -74.0060] }, // Mock, New York per test
    { id: 14, content: 'Migrazione umana in America via terra dopo lo scioglimento dei ghiacciai', start: "-014000-01-01", categories: ['Preistoria', 'Migrazioni'], description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti blanditiis cumque quisquam esse modi sed eos expedita, qui ratione aut vel beatae iste, officia numquam perspiciatis atque ad! Recusandae repellat magnam consequuntur accusantium modi quas, animi earum alias, id doloribus deserunt culpa cum vel cumque nam eaque magni obcaecati! Mollitia repellendus nisi voluptatum ab dignissimos expedita id minima excepturi laboriosam illum! Voluptatum odio, harum eos soluta quis accusantium dolore doloribus. Eveniet alias deleniti odio neque. Voluptate ipsa possimus expedita velit blanditiis laboriosam tempora laudantium veritatis alias, perspiciatis sunt voluptates aspernatur quidem tenetur. Ullam distinctio quo, repudiandae quos perspiciatis rerum rem blanditiis, eius, vero officiis neque magnam hic aperiam qui. Possimus, quaerat facere rem sequi nulla asperiores at excepturi dolor deserunt deleniti veniam dolorem quae omnis alias corporis magni repellat error ad molestias, ipsa inventore eos. Nobis nesciunt, blanditiis ut architecto dignissimos nam soluta corporis explicabo atque cum fugit aliquam delectus?", position: [64.2008, -149.4937] }, // Realtà: zona Alaska-Beringia
    { id: 15, content: 'Nascita primi centri urbani in Medio Oriente', start: "-009500-01-01", end: "-008500-01-01", categories: ['Preistoria', 'Urbanizzazione'], description: "Integer sollicitudin metus at ex sollicitudin, eget interdum risus volutpat.", position: [33.3128, 44.3615] }, // Realtà: area Mesopotamia (Baghdad)
    { id: 16, content: 'Villaggio di Gerico', start: "-008500-01-01", categories: ['Preistoria', 'Urbanizzazione'], description: "Duis tristique facilisis lectus, sed commodo dolor fermentum id.", position: [31.8700, 35.4433] }, // Realtà: Gerico
    { id: 17, content: 'In Anatolia nascono cittadine di migliaia di abitanti', start: "-007000-01-01", categories: ['Preistoria', 'Urbanizzazione'], description: "Aliquam erat volutpat. Proin imperdiet, nisl ut consequat convallis, nunc lorem egestas dui.", position: [37.6647, 32.6497] }, // Realtà: Çatalhöyük, Turchia
    { id: 18, content: 'Mezzaluna fertile si circonda di cittadine composte da decine di migliaia di persone', start: "-003000-01-01", end: "-002500-01-01", categories: ['Età Antica', 'Urbanizzazione'], description: "Nam fringilla est vitae justo convallis, et feugiat tortor venenatis.", position: [31.8700, 35.4433] }, // Realtà: Mezzaluna Fertile (usando Gerico)
    { id: 19, content: 'Basso Nilo viene riunito nel Primo Regno Egiziano', start: "-003100-01-01", categories: ['Età Antica', 'Regni e Imperi'], description: "Donec ut eros eget erat malesuada viverra nec in magna.", position: [30.0444, 31.2357] }, // Realtà: Cairo, Egitto
    { id: 20, content: 'Sargon Il Grande crea il primo Impero, quello Accadico', start: "-002250-01-01", categories: ['Età Antica', 'Regni e Imperi'], description: "Curabitur non felis bibendum, dapibus lorem sed, faucibus nulla.", position: [33.3128, 44.3615] }, // Realtà: Mesopotamia (Baghdad)
    { id: 21, content: 'Medio Oriente, nascita di vari Imperi', start: "-001000-01-01", end: "-000500-01-01", categories: ['Età Antica', 'Regni e Imperi'], description: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", position: [32.4279, 53.6880] } // Realtà: Persia (Iran)
];

export default events;
